masutil/autenticacion/urls.py
from django.urls import path

from .views import Vista_registro, cerrarSesion, loguear

app_name="autenticacion"
urlpatterns = [
   
    #COMO ES LAPRIMERA VISTA DE LA APP, LA RUTA VA DESDE LA RAIZ
    path('', Vista_registro.as_view(), name="Auth"),
    path('cerrar_sesion', cerrarSesion, name="cerrar_sesion"),
    path('loguear', loguear, name="loguear"),
]

masutil/carrito/urls.py
from django.urls import path
from . import views
#SE IMPORTAN PARA TENER ACCESO ALSETTINGS Y LOS ARCHIVOS MEDIA
from django.conf import settings
from django.conf.urls.static import static

app_name="carrito"

urlpatterns=[

    path('agregar/<int:producto_id>/',views.agregar_producto, name='agregar'),
    path('eliminar/<int:producto_id>/',views.elimiar_producto, name='eliminar'),
    path('restar/<int:producto_id>/',views.restar_producto, name='restar'),
    path('limpiar/',views.limpiar_carrito, name='limpiar'),
]
#permite acceso a media
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

masutil/masutil/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    #SE ENLAZA EL ARCHIVO URLS DE LA APLICACION
    path('masutilapp/', include('masutilapp.urls')),
    path('', include('servicios.urls')), ##AQUI SE ENCUENTRAN LAS CATEGORIAS O EL INDEX DE LA APP
    path('comercio/', include('comercio.urls')),
    path('contacto/', include('contactoapp.urls')),
    path('carrito/', include('carrito.urls')),
    path('autenticacion/', include('autenticacion.urls')),
]

masutil/masutilapp/urls.py
from django.urls import path

from masutilapp import views
#SE IMPORTA EL ARCHIVO SETTINGS PARA TENER A DISPOSICION MEDIA_URL Y MEDIA_ROOT
from django.conf import settings
#TAMBIEN SE DEBEN IMPORTAR LOS ARCHIVOS STATIC
from django.conf.urls.static import static

urlpatterns = [
   
    path('utiles/', views.utiles, name="Utiles"),
    #path('uniforme/', views.uniforme, name="Uniforme"),
    path('sobrenos/', views.sobrenos, name="Sobre nosotros"),
    path('advertencia/', views.advertencia, name="Advertencia"),
    #path('calificacion/', views.calificacion, name="Calificacion"),
    
    path('libros/', views.libros, name="Libros"),
    path('login/', views.login, name="Login"),
    path('mensaje/', views.mensaje, name="Mensaje"),
    #path('perfil/', views.perfil, name="Perfil"),
    path('registro/', views.registro, name="Registro"),
    
]
#SE AÑADE UNA NUEVA URL PARA VISUALIZAR LA IMAGEN DE LA CATEGORIA, LOS ELEMENTOS MEDIA_ SE ENCUENTRAN EN SETTINGS
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

masutil/masutilapp/views.py
from django.shortcuts import render, HttpResponse
#SE IMPORTAN LOS MODELOS DESDE MODELS A SER MOSTRADOS EN EL TEMPLATE, EN ESTE CASO LAS CATEGORIAS

# Create your views here.

#Se debe crear una vista por cada pagina del proyecto



def utiles(request):
    return render(request,"masutilapp/utiles.html")

def uniforme(request):
    return render(request,"masutilapp/uniformes.html")

def sobrenos(request):
    return render(request,"masutilapp/aboutUs.html")

def advertencia(request):
    return render(request,"masutilapp/advertencia.html")




#def cuaderno(request):
#    return HttpResponse("Cuaderno")

def libros(request):
    return render(request,"masutilapp/libros.html")

def login(request):
    return render(request,"masutilapp/login.html")

def mensaje(request):
    return render(request,"masutilapp/mensaje.html")



def registro(request):
    return render(request,"masutilapp/registro.html")

masutil/masutilapp/templates/masutilapp/aboutUs.html
<!DOCTYPE html>
<html lang="es">
{% extends "masutilapp/base.html"%}

{% load static%}
  
{% block content%}
<main class="pt-5 bg-primary">
    <div class="container-fluid mt-3 bg-primary">
   

  
    </div>
    <div class="container mt-3">
    <div class="row">
      <img src="reunion.png" class="mx-auto d-block" width="20" height="500">
        </div>
        <div class="row">
          <div class="mt-4 p-5 bg-warning text-secondary rounded">
            <h1>Sobre nosotros</h1>
            <p>En Más útil, nos dedicamos apasionadamente al desarrollo de software 
              innovador desde el aó 2024. Durante 1 año de trayectoria en la industria, 
              hemos superado con éxito los desafíos tecnológicos más exigentes y hemos colaborado con 
              numerosos clientes para transformar sus ideas en realidad.
              
              Nuestra misión es proporcionar soluciones a la medida que marquen la diferencia en el 
              mundo digital. Nos enorgullecemos de satisfacer a nuestros usuarios al ofrecerles 
              aplicaciones y sistemas altamente funcionales, seguros y atractivos que les ayudan a 
              sus necesidades relacionadas a la educación. La retroalimentación positiva de nuestros 
              clientes es nuestro mayor impulso y un testimonio de la calidad y compromiso que ponemos 
              en cada proyecto.
              
              Con una visión centrada en la innovación y el futuro, continuamos evolucionando y 
              adoptando las últimas tecnologías para asegurarnos de que nuestros clientes estén un paso 
              adelante en un mundo tecnológico en constante cambio.</p>
          </div>
        </div>
        
    </div>
</div>
</main>
{% endblock%}

masutil/masutilapp/templates/masutilapp/advertencia.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <div class="container-fluid-xl p-5 my-5 bg-primary text-white">

   
<header>
  <nav class="navbar navbar-expand-sm navbar-dark bg-secondary">
    <div class="container-fluid">
      <a class="navbar-brand" href="javascript:void(0)">Logo</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="mynavbar">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link" href="index.html">Inicio</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="javascript:void(0)">Sobre nosotros</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="javascript:void(0)">Contacto</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="registro.html">Registrarse</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="login.html">Iniciar sesión</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="perfil.html">Mi perfil</a>
          </li>
        </ul>
        
      </div>
    </div>
  </nav>
  
  <div class="container-fluid mt-3">
    <h3>Navbar Forms</h3>
    <p>You can also include forms inside the navigation bar.</p>
  </div>
</header>

  
<div class="container mt-5">
    <div class="alert alert-secondary">
        <strong>Atencion</strong> Datos invalidos <a href="#" class="alert-link">Error</a>.
      </div>
    <div class="row">
      <div class="col p-3 bg-warning text-white">
        
        <img src="utiles.jpg" class="float-start" alt="Paris" width="95%" height="95%">
      
        </div>
      <div class="col p-3 bg-primary text-white">
        
      </div>
      <div>
        <div class="row">
            <div class="col p-3 bg-primary text-white">
              
            </div>
            <div class="col p-3 bg-warning text-white">
              
              <img src="unforme.jpg" class="float-start" alt="Paris" width="95%" height="95%">
      </div>
</div>

  </body>
</html>

masutil/masutilapp/templates/masutilapp/base.html
<!DOCTYPE html>
<html lang="es">
<head>
  {% load static %}
  <title>Más útil</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
  <header>
    <div class="row  bg-secondary">
      <div style="text-align: right; margin-right: 100px;"> 
        {% if user.is_authenticated %}
         <span style="color: orange;"> Hola {{user.username}} </span>&nbsp;&nbsp; <a style="color: black;" href="{% url 'autenticacion:cerrar_sesion' %}">Cerrar sesion</a>

        {% else %}
        
        <a style="color:black" href="{% url 'autenticacion:Auth' %}">Registrarse</a> &nbsp;&nbsp;<a style="color: black;" href="{% url 'autenticacion:loguear' %}">Iniciar sesión</a>
      

        {% endif %}
      </div>
    </div>
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-secondary">
        <div class="container-fluid">
            <img src="{%static 'masutilapp/img/logo.png' %}" alt="15" width="50" height="50">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="mynavbar">
            <ul class="navbar-nav me-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'Inicio' %}">Inicio</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'Sobre nosotros' %}">Sobre nosotros</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'Contacto' %}">Contacto</a>
              </li>
              
             
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'Perfil' user.id %}">Mi perfil</a>
              </li>
              {% endif %}
            </ul>
            
          </div>
        </div>
      </nav>
    </header>
    {% block content%}

    
    {% endblock %}
    <footer class="bg-secondary p-3">
      <div class="container text-center">
        
        <small class="text-white">
          &copy; 2023 Más útil, dale más vida a tu aprendizaje 
        </small>
      </div>
    </footer>
  </body>
</html>

masutil/masutilapp/templates/masutilapp/contact.html
{% extends "masutilapp/base.html"%}

{% load static%}

{% block content%}
<main class="pt-5 bg-primary">
    <div class="container-fluid mt-3 bg-primary">
    <div class="container-fluid mt-3">
    

    
    <div class="container-fluid">
        <div class="row">
            <h2>Datos de contacto para PQRS</h2>
  
  
  <table class="table">
    <thead class="table-success">
      <tr>
        <th>Nombre</th>
        <th>Dependencia</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Jhonny Cañon</td>
        <td>Area de soporte tecnico</td>
        <td>jhoncanon@masutil.com</td>
      </tr>
      <tr>
        <td>Leonel Mendez</td>
        <td>Atencion al cliente</td>
        <td>leonelmendez@masutil.com</td>
      </tr>
      
    </tbody>
  </table>

        </div>
    </div>
    </div>
</div>
</main>

{% endblock%}

masutil/masutilapp/templates/masutilapp/libros.html
{% extends "masutilapp/base.html"%}

{% load static%}

{% block content%}
<main class="pt-5 bg-primary">
    <div class="container-fluid mt-5 bg-primary">
    <div class="container-fluid mt-3">
    <div class="row">
        
    
    
    
<div class="col p-3">

  
  <form action="/action_page.php">
    <div class="form-floating mb-3 mt-3">
      <select class="form-select" id="sel1" name="sellist">
        <option>Matematicas</option>
        <option>Español</option>
        <option>Sociales</option>
        <option>Literatura</option>
      </select>
      <label for="sel1" class="form-label">Selecccione tipo de libro (seleccione una):</label>
    </div>
    
  </form>
</div>

<div class="col p-3">
    
  
        <form action="/action_page.php">
          <div class="form-floating mb-3 mt-3">
            <select class="form-select" id="sel2" name="sellist2">
              <option>Primaria</option>
              <option>Secundaria</option>
              <option>Media académica</option>
              <option>Educación superior</option>
              
            </select>
            <label for="sel2" class="form-label">Seleccione grado (seleccione una):</label>
          </div>
          
        </form>
      </div>

      <div class="row">
        <div class="col-3">
          <button type="button" class="btn btn-secondary text-info active">Buscar</button>
    </div>
</div>
    </div>
    </div>
    <div class="container-fluid mt-3">
      <div class="row">
          <div class="col">
<!--   imagen -->
          
      <h2>Libro</h2>
      <div class="card bg-warning text-primary" style="width:400">
        <img class="card-img-top" src="librousado.jpg" alt="Card image" style="width:100%">
        <div class="card-body">
          <h4 class="card-title">Literatura, educacion superior</h4>
          
          <a href="#" class="btn btn-secondary text-info">Reservar</a>
        </div>
      </div>
          </div>
          <div class="col">
<!--   info -->
            <h2>Descripción</h2>
            <div class="mt-4 p-5 bg-secondary text-info rounded">
              <h1>Libro de Matemáticas de grado segundo</h1> 
              <p>Libro de matemáticas para grado segundo en estado 9/10, precio cómodo  </p> 
            </div>
        </div>
      </div>
    </div>
</div>
</main>
{% endblock%}

masutil/masutilapp/templates/masutilapp/mensaje.html
{% extends "masutilapp/base.html"%}

{% load static%}

{% block content%}
    <main class="pt-5 bg-primary">
        <div class="container mt-3 bg-primary">
            <div class="container mt-3">
                <div class="row">    
                    <div class="col p-3">                                      
                        <div class="form-floating mb-3 mt-3">
                            <img src="perfil.png" alt="50%" width="50%">
                        </div>                     
                    </div>
                    <div class="col p-3">                         
                          <div class="mt-4 p-5 bg-secondary text-info rounded">     
                            <h1>Julieta Román</h1> 
                                <p>Calificación: 4.5 <br>
                                    Número de calificaciones: 343 
                                    <a href="calificacion.html">Ir</a>
                                </p>                        
                            </div>                                 
                    </div>                        
                    <div class="container-fluid mt-3">
                        <div class="row">
                            <div class="mt-4 p-5 bg-secondary text-info rounded">     
                                <h1>Mensaje</h1> 
                                    <p>Hola, mi nombre es Diego estoy interesado en el uniforme que publicaste ya hice la reserva me podrias informar cuando puedes realizar el intercambio
                                    </p>                        
                                </div>                               
                        </div>
                    </div>
                    <div class="row">                        
                            <div class="text-center">
                                <button type="button" class="btn btn-secondary text-info active text-center">Enviar</button> 
                            </div>                        
                    </div>
                </div>
            </div>           
        </div>
    </main>
{% endblock%}

masutil/masutilapp/templates/masutilapp/registro.html
{% extends "masutilapp/base.html"%}

{% load static%}

{% block content%}
  <main class="pt-5 bg-primary">
     
<div class="container mt-5">
    <div class="row">
      <div class="col p-3 bg-warning text-white">
        <div class="container">
            <img src="utiles.jpg" class="mx-auto d-block rounded" alt="Paris" width="95%" height="95%">
        </div><br>
        <div class="container" >
            <img src="unforme.jpg" class="mx-auto d-block rounded" alt="Paris" width="95%" height="95%">
        </div>
      </div>
      <div class="col p-3 bg-primary text-white">
        
        <div class="container-md bg-secondary p-3">
          
          
          
            <form action="/action_page.php">
              <div class="mb-3 mt-3 text-info">
                <label for="nombre" >Nombre:</label>
                <input type="text" class="form-control bg-primary" id="nombre" placeholder="Digite nombres" name="nombre">
              </div>
              <div class="mb-3 text-info">
                <label for="apellido">Apellidos:</label>
                <input type="text" class="form-control bg-primary" id="apellido" placeholder="Digite apellidos" name="apellido">
              </div>
              <div class="mb-3 mt-3 text-info">
                <label for="email" >Email:</label>
                <input type="email" class="form-control bg-primary" id="email" placeholder="Enter email" name="email">
              </div>
              <div class="mb-3 text-info">
                <form action="/action_page.php">
                  <div class="form-floating mb-3 mt-3 bg-primary">
                    <select class="form-select bg-primary" id="sel1" name="sellist">
                      <option>Tarjeta de identidad</option>
                      <option>Cedula de ciudadania</option>
                      <option>Cedula de extranjeria</option>
                    
                    </select>
                    <label for="sel1" class="form-label">Selecccione tipo de NUIP (seleccione una):</label>
                  </div>
                  
                </form>
              </div>
              <div class="mb-3 mt-3 text-info">
                <label for="nuip" >NUIP:</label>
                <input type="number" class="form-control bg-primary" id="tnuip" placeholder="Digite NUIP" name="nuip">
              </div>
              <div class="mb-3 text-info">
                <label for="fecha">Fecha de nacimiento:</label>
                <input type="date" class="form-control bg-primary" id="fecha" placeholder="Digite fecha de nacimiento" name="fecha">
              </div>
              <div class="mb-3 text-info">
                <label for="pwd">Contrasena:</label>
                <input type="password" class="form-control bg-primary" id="pwd" placeholder="Digite contrasena" name="pswd">
              </div>
              <div class="form-check mb-3 text-info">
                <label class="form-check-label">
                  <input class="form-check-input" type="checkbox" name="remember"> Recordarme
                </label>
              </div>
              <button type="submit" class="btn btn-primary">Registro</button>
            </form>
        </div>
    </div>
  </div>

</div>

        
  </main>
{% endblock%}

masutil/masutilapp/templates/masutilapp/utiles.html
{% extends "masutilapp/base.html"%}

{% load static%}

{% block content%} 
  <main class="pt-5 bg-primary">
    <div class="container-fluid mt-3 bg-primary">
    <div class="container-fluid mt-3">
    <div class="row">
    <div class="col p-3">

  
  <form action="/action_page.php">
    <div class="form-floating mb-3 mt-3">
      <select class="form-select" id="sel1" name="sellist">
        <option>Para escribir</option>
        <option>Para tomar apuntes</option>
        <option>Para guardar otros útiles</option>
        <option>Otro</option>
      </select>
      <label for="sel1" class="form-label">Selecccione tipo de útil (seleccione una):</label>
    </div>
    
  </form>
</div>

      <div class="col p-3">
    
      </div>

      <div class="row">
        <div class="col-3">
          <button type="button" class="btn btn-secondary text-info active">Buscar</button>
    </div>
</div>
    </div>
    </div>
    <div class="container-fluid mt-3">
    <div class="row">
        <div class="col">
<!-- imagen -->

    <h2>Útiles</h2>
    <div class="card bg-warning text-primary" style="width:400">
      <img class="card-img-top" src="utillapiz.JPG" alt="Card image" style="width:100%">
      <div class="card-body">
        <h4 class="card-title">Set de lapices y colores</h4>
        <p>Precio: $1000<br>
          Unidades: 10 <br>

        </p>
        <a href="#" class="btn btn-secondary text-info">Reservar</a>
      </div>
    </div>
        </div>
        <div class="col">
<!-- info -->
<h2>Descripción</h2>
<div class="mt-4 p-5 bg-secondary text-info rounded">
  <h1>Set de lapices y colores</h1> 
  <p>Lapices y colores variados, con una vida util aun larga, a precio bajo</p> 
</div>
        </div>
    </div>
</div>
</div>
</main>
{% endblock%}