masutil/carrito/urls.py
from django.urls import path
from . import views
#SE IMPORTAN PARA TENER ACCESO ALSETTINGS Y LOS ARCHIVOS MEDIA
from django.conf import settings
from django.conf.urls.static import static

app_name="carrito"

urlpatterns=[

    path('agregar/<int:producto_id>/',views.agregar_producto, name='agregar'),
    path('eliminar/<int:producto_id>/',views.elimiar_producto, name='eliminar'),
    path('restar/<int:producto_id>/',views.restar_producto, name='restar'),
    path('limpiar/',views.limpiar_carrito, name='limpiar'),
]
#permite acceso a media
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

masutil/comercio/urls.py
from django.urls import path
from . import views
#SE IMPORTAN PARA TENER ACCESO ALSETTINGS Y LOS ARCHIVOS MEDIA
from django.conf import settings
from django.conf.urls.static import static


urlpatterns=[

    path('perfil/<int:usuario_id>/',views.perfil, name='Perfil'),
    path('perfil/NProductos/<int:usuario_id>/',views.n_producto, name='nuevo_producto'),
    path('perfil/EProductos/<int:producto_id>//<int:usuario_id>/',views.e_producto, name='elimina_producto'),
    path('perfil/Editar/<int:producto_id>//<int:usuario_id>/',views.editar,name="editar"),
    path('perfil/Uniformes/<int:id_categoria_id>/', views.uniforme, name="Uniforme"),
    path('perfil/factura/', views.procesar_factura, name="Factura"),
    path('perfil/calificar/<int:publicacion_id>/', views.calificacion, name="Calificar"), 
    path('perfil/micalifica/<int:usuario_id>/', views.mi_calificacion, name="mi_calificacion"),   
    
    path('perfil/Uniformes/2/', views.uniforme, name="Uniforme2"),#linea provisional para que funcione carrito con id categoria =2
]
#permite acceso a media
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

masutil/masutil/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    #SE ENLAZA EL ARCHIVO URLS DE LA APLICACION
    path('masutilapp/', include('masutilapp.urls')),
    path('', include('servicios.urls')), ##AQUI SE ENCUENTRAN LAS CATEGORIAS O EL INDEX DE LA APP
    path('comercio/', include('comercio.urls')),
    path('contacto/', include('contactoapp.urls')),
    path('carrito/', include('carrito.urls')),
    path('autenticacion/', include('autenticacion.urls')),
]

masutil/comercio/models.py
from django.db import models
from servicios.models import categoria
from django.contrib.auth.models import User
# Create your models here.

class usuarios(models.Model):
    id_usuario=models.AutoField(primary_key=True);
    nombre=models.CharField(max_length=50, null=False);
    documento=models.IntegerField(null=False,unique=True);
    email=models.EmailField(null=False, max_length=30);
    username=models.CharField(max_length=50);
    password=models.CharField(max_length=50,null=False);

    class Meta:
        verbose_name='comprador'
        verbose_name_plural='compradores'

    def __str__(self):
        return self.documento;

class productos(models.Model):
    id_producto=models.AutoField(primary_key=True);
    id_categoria=models.ForeignKey(categoria, on_delete=models.CASCADE);
    nombre_producto=models.CharField(max_length=70);
    valor=models.IntegerField();
    descripcion=models.CharField(max_length=50);
    imagen=models.ImageField(upload_to='comercio');#CREA SUBCARPETA DENTRO DE MEDIA DONDE SE GUARDAN LAS IMAGENES, MEDIA SE CONFIGURA EN SETTINGS
    
    class Meta:
        verbose_name='producto'
        verbose_name_plural='productos'

    def __str__(self):
        return self.nombre_producto;

class facturaVenta(models.Model):
    id_factura=models.AutoField(primary_key=True);
    id_usuario=models.ForeignKey(User, on_delete=models.CASCADE);
    orderDate=models.DateTimeField(auto_now_add=True);
    valor=models.IntegerField();
    descripcion=models.CharField(max_length=100)
    medioDePago=models.CharField(max_length=50, null=True);

class publicaciones(models.Model):
    id_publicacion=models.AutoField(primary_key=True);
    id_usuario=models.ForeignKey(User,on_delete=models.CASCADE);
    id_producto=models.ForeignKey(productos, on_delete=models.CASCADE);
    fecha_publicacion=models.DateTimeField(auto_now=True);

class ventas(models.Model):
    id_venta=models.AutoField(primary_key=True);
    id_producto=models.ForeignKey(productos, on_delete=models.CASCADE);
    id_factura=models.ForeignKey(facturaVenta, on_delete=models.CASCADE);
    
    
class retroalimentacion(models.Model):
    id_retroalimentacion=models.AutoField(primary_key=True);
    id_usuario=models.ForeignKey(User, on_delete=models.CASCADE);
    id_publicacion=models.ForeignKey(publicaciones, on_delete=models.CASCADE);
    puntaje=models.IntegerField();
    descripcion=models.CharField(max_length=50);

class conversaciones(models.Model):
    id_conversacion=models.AutoField(primary_key=True);
    fecha=models.DateTimeField(auto_now=True);
    contenido=models.CharField(max_length=200);

class miembros_conversacion(models.Model):
    id_miembros=models.AutoField(primary_key=True);
    id_usuario=models.ForeignKey(User, on_delete=models.CASCADE);
    id_conversacion=models.ForeignKey(conversaciones, on_delete=models.CASCADE);

masutil/comercio/forms.py
from django import forms

from .models import productos, retroalimentacion

class nproductoForm(forms.ModelForm):

    class Meta:
        model = productos;
        
        fields = ('id_producto','nombre_producto','id_categoria','valor','descripcion','imagen');
        

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)#Trae las categorias disponibles desde la BBDD
        self.fields['nombre_producto'].required=False;
        self.fields['valor'].required=False;
        self.fields['descripcion'].required=False;
        self.fields['imagen'].required=False;
        
        self.fields['id_categoria'].widget.attrs.update({
            'class': 'form-select'
        })
      

class edicionForm(forms.ModelForm):

    class Meta:
        model = productos;
        
        fields = ('id_producto','nombre_producto','id_categoria','valor','descripcion','imagen');
        

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)#Trae las categorias disponibles desde la BBDD
        self.fields['nombre_producto'].required=False;
        self.fields['valor'].required=False;
        self.fields['descripcion'].required=False;
        self.fields['imagen'].required=False;
        
        self.fields['id_categoria'].widget.attrs.update({
            'class': 'form-select'
        })


class new_calificationForm(forms.Form):
    opciones = (
         ("1","uno"),
         ("2","dos"),
         ("3","tres"),
         ("4","cuatro"),
         ("5","cinco"),
     )
    puntaje = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, choices=opciones, )
                                           
    descripcion=forms.CharField(label="Descripcon",required=True, max_length=750,widget=forms.Textarea);
    

masutil/comercio/views.py
from django.shortcuts import render, redirect
from comercio.models import publicaciones, productos, User, facturaVenta, ventas, retroalimentacion
from carrito.carrito import carrito
from django.contrib import messages
from .forms import nproductoForm, new_calificationForm, edicionForm
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.core.mail import send_mail

# Create your views here.

#SE ESPERA QUE EN LA VISTA PERFIL APAREZCAN LOS PRODUCTOS CARGADOS POR EL USUSARIO
def perfil(request,usuario_id):#Se traen todas las publicaciones hechas por el usuario autenticado
    publicacion=publicaciones.objects.filter(id_usuario_id=usuario_id)
    return render(request,"comercio/perfil.html",{"publicacion":publicacion})

def n_producto(request,usuario_id):
    productoNuevo=nproductoForm;
    user = User.objects.get(id=usuario_id)
    print(user.id)
    if request.method=="POST":
        productoNuevo=nproductoForm(request.POST, request.FILES)
        #print("entro al post")
        if productoNuevo.is_valid():            
            productoNuevo.save();
            producto=productos.objects.last()
            idproducto=producto.id_producto
            publicacion=publicaciones(id_usuario_id=user.id,id_producto_id=idproducto)
            publicacion.save()
            #print("conseguido")
            return redirect("Perfil", usuario_id)
        else:
            #print("rechazado")
            for field in productoNuevo:
                print("Field Error:", field.name,  field.errors)
            return render(request,"comercio/nuevos_productos.html",{"prodnuevo":productoNuevo})
            
    else:
        pass
        #print("no utl")
    return render(request,"comercio/nuevos_productos.html",{"prodnuevo":productoNuevo})

def editar(request,producto_id, usuario_id):
    edicion_producto=edicionForm;
    
    redirect("nuevo_producto", usuario_id);

        
def calificacion(request, publicacion_id):
    formulario_calificacion=new_calificationForm;#SE INSTANCIA EL OBJETO FORMULARIO
    if request.method=="POST":
        formulario_calificacion=new_calificationForm(data=request.POST);#se cargan en el formulario la informacion introducida para rescatar de los cuadros de texto
        if formulario_calificacion.is_valid():
            puntaje=request.POST.get("puntaje");#se guaradn en variables los datos suministrados por el usuario
            descripcion=request.POST.get("descripcion");
            calificar=retroalimentacion(id_usuario=request.user,id_publicacion_id=publicacion_id,puntaje=puntaje,descripcion=descripcion);
            calificar.save()

        return redirect("Factura")
    return render(request,"comercio/calificacion.html",{"calificacion":formulario_calificacion})

def mi_calificacion(request,usuario_id):#Debe llamarse igual al que esta en la url
    
    feedback=retroalimentacion.objects.filter(id_usuario=usuario_id);
  
    
    return render(request, "comercio/micalificacion.html",{"retro":feedback})

def e_producto(request, producto_id, usuario_id):
    mi_producto=publicaciones.objects.filter(id_producto=producto_id);
    mi_producto.delete()
    return redirect("Perfil", usuario_id)


def uniforme(request,id_categoria_id):
    
    #uniforme=productos.objects.filter(id_categoria=id_categoria_id);#SE FILTRA POR CATEGORIA CUANDO USUARIO HACE CLIC EN ENLACE
    
    publicacion=publicaciones.objects.filter(id_producto__id_categoria=id_categoria_id);# SE MUESTRAN LAS PUBLICACIONES ASOCIADAS A LA CATEGORIA ANTERIOR
   
    return render(request,"comercio/uniformes.html",{"uniformes":uniforme,"publicacion":publicacion})#EN EL RENDERIZADO SE MUESTRAN LOS PRODUCTO CORRESPONDIENTES A LA CATGERIA FILTRADA 

def procesar_factura(request):
    #factura=facturaVenta.objects.create(id_usuario=request.user,valor=23)#Se almacena lo que ha pedido el cliente
    carro=carrito(request)
    productosFactura=list()
    for key, value in carro.carro.items():
        productosFactura.append(facturaVenta(
            id_usuario=request.user,
            #cantidad=value["cantidad"],
            valor=value["precio"],
            descripcion=str(value["cantidad"])+" "+value["nombre"],
            medioDePago="No aplica por ahora",
            #factura=factura

        ))
        usuario=value["usuario"]
        
        correo=value["correo"]
        producto_actual=value["producto_id"];
        publicacions=publicaciones.objects.get(id_producto=producto_actual);
        publicacion_id=publicacions.id_publicacion;
    print(publicacions)
    
    #con este metodo se inserta en la base de datos es como tener muchos insert into
    ultimas_facturas=facturaVenta.objects.bulk_create(productosFactura)
    for ultimo in ultimas_facturas:
        idfactura=ultimo.id_factura
    
    
        print(facturaVenta.id_factura)
        venta=ventas(id_producto_id=producto_actual,id_factura_id=idfactura)
        venta.save();

#Se debe revisar el envio del mail cuando se corrija para que le llegue a todos los vendedores
    #enviar_mail(
    #    #factura=factura,
    #    productosFactura=productosFactura,
    #    comprador=request.user.username,
    #    email_comprador=request.user.email,
    #    vendedor=usuario,
    #    email_vendedor=correo
    #    )
#
    #messages.success(request, "El pedido se ha creado correctamente")
    return redirect("Calificar",publicacion_id)

def enviar_mail(**kwargs):# De esta manera a funcion esta preparada para recibir una cantidad indetermindada de argumentos
    asunto=" Reserva completada",
    mensaje=render_to_string("emails/facturas.html",{
        #"factura":kwargs.get("factura"),
        "productosFactura":kwargs.get("productosFactura"),
        "nombreusuario":kwargs.get("comprador"),
        
    })

    mensaje_texto=strip_tags(mensaje)#De esta manera se omiten etiquetas de html
    from_email=kwargs.get("email_comprador");
    to=kwargs.get("email_vendedor");
     
    send_mail(asunto,mensaje_texto,from_email,[to],html_message=mensaje)

masutil/comercio/templates/comercio/calificacion.html
{% extends "masutilapp/base.html"%}

{% load static%}

{% block content%}
    <main class="pt-5 bg-primary">
        <div class="container mt-3 bg-primary">
            <div class="container mt-3">
                <div class="row">    
                    <!-- <div class="col p-3">                                      
                        <div class="form-floating mb-3 mt-3">
                            <img src="perfil.png" alt="50%" width="50%">
                        </div>                     
                    </div>
                    <div class="col p-3">                         
                          <div class="mt-4 p-5 bg-secondary text-info rounded">     
                            <h1>Julieta Román</h1> 
                                <p>Calificación: 4.5 <br>
                                    Número de calificaciones: 343   
                                </p>                        
                            </div>                                 
                    </div>                        
                    <div class="container-fluid mt-3">
                        <div class="row">
                            <div class="mt-4 p-5 bg-secondary text-info rounded">     
                              <table class="table table-striped">
                                <thead>
                                  <tr>
                                    <th>Usuario</th>
                                    <th>Calificación</th>
                                    <th>Comentario</th>
                                  </tr>
                                </thead>
                                <tbody>
                                  <tr>
                                    <td>Juanito Caden</td>
                                    <td>4.8</td>
                                    <td>Es la mejor vendedora</td>
                                  </tr>
                                  <tr>
                                    <td>Alan Britos</td>
                                    <td>4.5</td>
                                    <td>Excelente uniforme a precio unico</td>
                                  </tr>
                                  <tr>
                                    <td>Dolan Teuns</td>
                                    <td>4.7</td>
                                    <td>Los lapices que me vendio han salido muy buenos</td>
                                  </tr>
                                </tbody>
                              </table>                      
                            </div>                               
                        </div>
                    </div>
                    <div class="row">                        
                            <div class="text-center">
                                <button type="button" class="btn btn-secondary text-info active text-center">Regresar</button> 
                            </div>                        
                    </div> -->
                
                    <form action="" method="POST" style="text-align: center;">
                      {% csrf_token %}
                      <table style="margin: 20px auto;">
                        {% load crispy_forms_filters %} 
                        {% load crispy_forms_tags %}
                        {{calificacion | crispy}}
                    </table>
                    <input type="submit" value="Enviar" style="width: 150px;">
                  </form>
                  </div>
            </div>           
        </div>
    </main>
{% endblock%}

masutil/comercio/templates/comercio/micalificacion.html
{% extends "masutilapp/base.html"%}

{% load static%}

{% block content%}
    <main class="pt-5 bg-primary">
        <div class="container mt-3 bg-primary">
            <div class="container mt-3">
                <div class="row">    
                    {% for feedback in retro %}
                        <div>
                            <h4>{{feedback.id_usuario}}</h4>
                            <h4>{{feedback.puntaje}}</h4>
                            <h4>{{feedback.descripcion}}</h4>
                            <h4>{{feedback.id_publicacion}}</h4>
                            
                        </div>
                    {% endfor %}
                
                </div>
            </div>           
        </div>
    </main>
{% endblock%}

masutil/comercio/templates/comercio/nuevos_productos.html
{% extends "masutilapp/base.html"%}

{% load static%}

{% block content%}
<main class="pt-5 bg-primary">
   
  <div class="contenedorFormulario">
<!-- Una vez se recibe la palabra valido que implica el envio de POST se muestra la comporbacion de que se ha recibido la informacion -->
    
    <form method="POST" action="" enctype="multipart/form-data" style="text-align: center;">
      {% csrf_token %}
      <table style="margin: 20px auto;">
      {{prodnuevo.as_ul}}
    </table>
    <button type="submit" class="btn btn-success text-info">Publicar</button> 
  </form>
  </div>
</main>

{% endblock%} 

masutil/comercio/templates/comercio/perfil.html
{% extends "masutilapp/base.html"%}

{% load static%}

{% block content%}
    <main class="pt-5 bg-primary">
        <div class="container mt-3 bg-primary">
            <div class="container mt-3">
                <div class="row">    
                    <div class="col p-3">                                      
                        <div class="form-floating mb-3 mt-3">
                            <img src="{%static 'masutilapp/img/perfil.png' %} " alt="50%" width="50%">
                        </div>                     
                    </div>
                    <div class="col p-3">                         
                          <div class="mt-4 p-5 bg-secondary text-info rounded">     
                            <h1>{{publicacion.id_usuario.name}}</h1> 
                                <p>Calificación: 4.5 <br>
                                    Número de calificaciones: 343  
                                    <div class="text-center">
                                        <a href="{% url 'mi_calificacion' user.id %}" style="color: black;" >Ir a mis calificaciones</a> 
                                    </div> 
                                </p>                        
                            </div>                                 
                    </div>                        
                    <div class="container-fluid mt-3">
                        <div class="row">                        
                            <div class="text-center bg-secondary">
                                <h3>Mis productos</h3>
                            </div>                        
                        </div>
                        {% if user.is_authenticated %}
                        <div class="container-fluid mt-3">   
                            <div class="row">
                                {% for comercio in publicacion %}
                                <div class="col-sm-4">   
                                    <div class="card bg-warning text-white">
                                        <img class="mx-auto d-block rounded" src="{{comercio.id_producto.imagen.url}}" alt="Card image" style="width:250px; height:250px" >
                                        <div class="card-body">
                                            <h4 class="card-title">Libro: {{comercio.id_producto}} <br>Precio: ${{comercio.id_producto.valor}} <br>Descripcion: {{comercio.id_producto.descripcion}}</h4>
                                            <div class="row">
                                                <div class="col">
                                                    <div class="text-center">
                                                        <a href="{% url 'editar' comercio.id_producto.id_producto user.id %}">Editar</a>  
                                                    </div>
                                                </div>
                                                <div class="col">
                                                    <div class="text-center">
                                                        <a href="{% url 'elimina_producto' comercio.id_producto.id_producto user.id %}">Remover</a> 
                                                    </div>
                                                </div>  
                                            </div>
                                        </div>
                                    </div>                                                          
                                </div>
                                {% endfor %} 
                                                        
                            </div>

                            
                        </div>
       
                    </div>
                    <div class="row">                        
                            <div class="text-center">
                                <a href="{% url 'nuevo_producto' user.id %}" style="color: black;" >Agregar producto</a> 
                            </div>                        
                    </div>
                    {% endif %}
                </div>
            </div>           
        </div>
    </main>
{% endblock%}

masutil/comercio/templates/comercio/uniformes.html
{% extends "masutilapp/base.html"%}

{% load static%}

{% block content%}
    <main class="pt-5 bg-primary">
        <div class="container mt-3 bg-primary">
            
            <div class="row">    
                <div class="input-group">
                  <input type="search" class="form-control rounded" placeholder="Search" aria-label="Buscar" aria-describedby="search-addon" />
                   <button style="background-color: grey; color:orange;" type="button" class="btn btn-outline-warning" data-mdb-ripple-init>Buscar</button>
                </div>
            </div>
          </div>
            

            <div class="container-fluid mt-3">
              <div style="float:right ;">

              {% if request.user.is_authenticated %}
                {% include "carrito/widget.html" %}

              {% else %}
                <p>Login requerido para ver carro</p>
              {% endif %}

              <!-- <p>Total:  ${{importe_total_carrito}}</p> -->
              </div>
              <div class="row">
              {% for comercio in publicacion%}
                {% if comercio.id_usuario_id != user.id %}
                    <div class="col-sm-4">
    <!-- imagen -->
    <!-- COMERCIO ES EQUIVALENTE A PUBLICACION SE LLAMA ASI PORQUE YA ASI SE DENOMINADA LOS ARCHIVOS MEDIA -->
                      <div class="card bg-warning text-white">
                        <h3>{{comercio.id_producto}}</h3>
                        
                            <img  class="mx-auto d-block rounded" src="{{comercio.id_producto.imagen.url}}" alt="Card image" style="width:100%">
                            <div class="card-body text-center">
                              <h4 class="card-title">{{comercio.id_producto.descripcion}}</h4>  
                              <h4 class="card-title">${{comercio.id_producto.valor}}</h4>
                              <h4 class="card-title">${{comercio.id_producto.valor}}</h4>
                                <a href="{% url 'carrito:agregar' comercio.id_producto.id_producto %}" class="btn btn-success text-info">Agregar al carro</a>
                            </div>
                        
                      </div>
                    </div>
                    {% endif %}
                {%endfor%}
              </div>
            </div>
        </div>
    </main>
{% endblock%}